apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/your-org/terraform-azure-openshift.git'
    targetRevision: HEAD
    path: manifests/

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

