trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Trigger_Tekton
    jobs:
      - job: StartTekton
        steps:
          - script: |
              kubectl create -f pipelines/tekton-ci.yml
            displayName: "Start Tekton pipeline"