trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Deploy_ArgoCD
    jobs:
      - job: StartArgoCD
        steps:
          - script: |
              curl -X POST -H "Content-Type: application/json" \
              --data '{"image":"myazureacr.azurecr.io/my-app:latest"}' \
              http://argocd-webhook-url
            displayName: "Trigger ArgoCD Sync"