trigger: none

pool:
    vmImage: ubuntu-latest

variables:
    - name: ARM_CLIENT_ID
      value: ${AZURE_CLIENT_ID}
    - name: ARM_CLIENT_SECRET
      value: ${ARM_CLIENT_SECRET}
    - name: ARM_SUBSCRIPTION_ID
      value: ${AZURE_SUBSCRIPTION_ID}
    - name: ARM_TENANT_ID
      value: ${AZURE_TENANT_ID}

stages:
    - stage: Terraform_Provision
      jobs:
        - job: ApplyTerraform
          steps:
            - checkout: self
            - task: TerraformInstaller@0
              inputs:
                terraformVersion: 'latest'

            - script: |
                terraform init
                terraform plan -out=tfplan
              displayName: "Terraform Init & Plan"

            - script: |
                terrform apply -auto-approve tfplan
              displayName: "Terraform Apply"
